/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ReturnBook;
import Controller.SearchMember;
import Model.DB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class BookReturning extends javax.swing.JDialog {

    /**
     * Creates new form BookReturning
     */
    public BookReturning(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtFine.setEditable(false);
        txtBookId.setEditable(false);
        txtMemberId.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMembers = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBorrowedBooks = new javax.swing.JTable();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        txtSearchMember = new javax.swing.JTextField();
        btnSearchMember = new javax.swing.JButton();
        txtMemberId = new javax.swing.JTextField();
        txtBookId = new javax.swing.JTextField();
        txtFine = new javax.swing.JTextField();
        lblMemberId = new javax.swing.JLabel();
        lblBookId = new javax.swing.JLabel();
        lblFine = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblSearch1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        lblHeading.setText("Return Books");

        tblMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "First Name", "Last Name"
            }
        ));
        tblMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMembersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMembers);

        tblBorrowedBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "Book ID", "Book Title", "Borrowed Date", "Due Date", "Is Returned"
            }
        ));
        tblBorrowedBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBorrowedBooksMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBorrowedBooks);

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle1.setText("Members");

        lblTitle2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle2.setText("Borrowed Books");

        btnSearchMember.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSearchMember.setText("SEARCH");
        btnSearchMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMemberActionPerformed(evt);
            }
        });

        txtMemberId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtBookId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtFine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblMemberId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMemberId.setText("Member ID");

        lblBookId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBookId.setText("Book ID");

        lblFine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFine.setText("Fine(Rs.)");

        btnReturn.setBackground(new java.awt.Color(51, 255, 0));
        btnReturn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReturn.setText("<<Return Book");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 102, 102));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblSearch1.setText("(search by ID)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeading)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMemberId)
                            .addComponent(lblBookId)
                            .addComponent(lblFine))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMemberId)
                            .addComponent(txtBookId)
                            .addComponent(txtFine, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTitle1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblSearch1)
                            .addGap(197, 197, 197))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtSearchMember, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchMember)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHeading)
                                    .addComponent(lblTitle1)
                                    .addComponent(lblSearch1))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSearchMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearchMember))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblMemberId))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(txtMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBookId))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFine)
                            .addComponent(txtFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturn)
                    .addComponent(btnCancel))
                .addGap(18, 18, 18)
                .addComponent(lblTitle2)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        setSize(new java.awt.Dimension(707, 525));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         try{
            Connection con=DB.createConnection();
            Statement st=con.createStatement();
            String sql="select * from members";
            ResultSet rst=st.executeQuery(sql);
            
            while(rst.next()){
             String memberId=rst.getString("memberId");
             String firstName=rst.getString("firstName");
             String lastName=rst.getString("lastName");
             
             String tblData[]={memberId,firstName,lastName};
             DefaultTableModel tblModel=(DefaultTableModel)tblMembers.getModel();
             tblModel.addRow(tblData);
            }
            con.close();
        }catch(Exception e){
            e.printStackTrace();
            System.out.println("Error"+e.getLocalizedMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnSearchMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMemberActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel=(DefaultTableModel)tblMembers.getModel();
        tblModel.setRowCount(0);
        SearchMember searchMember=new SearchMember();
        searchMember.searchMemberById1(txtSearchMember.getText(), tblModel);
    }//GEN-LAST:event_btnSearchMemberActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMembersMouseClicked
        // TODO add your handling code here:
         DefaultTableModel tblModel=(DefaultTableModel)tblMembers.getModel();
        int selectedRowIndex=tblMembers.getSelectedRow();
        txtMemberId.setText(tblModel.getValueAt(selectedRowIndex, 0).toString());
        txtFine.setText(null);
        DefaultTableModel tblModel2=(DefaultTableModel)tblBorrowedBooks.getModel();
        tblModel2.setRowCount(0);
        try{
            Connection con=DB.createConnection();
            Statement st=con.createStatement();
            String sql="select M.memberId,M.bookId,B.bookTitle,M.borrowedDate,M.dueDate,M.isReturned from borrowed_books M,books B where M.bookId=B.bookId and M.memberId='"+txtMemberId.getText()+"' and M.isReturned='"+"No"+"'";
            ResultSet rst=st.executeQuery(sql);
            
            while(rst.next()){
             String memberId=rst.getString("memberId");
             String bookId=rst.getString("bookId");
             String bookTitle=rst.getString("bookTitle");
             String borrowedDate=rst.getString("borrowedDate");
             String dueDate=rst.getString("dueDate");
             String isReturned=rst.getString("isReturned");
             
             String tblData[]={memberId,bookId,bookTitle,borrowedDate,dueDate,isReturned};
             DefaultTableModel tblModel1=(DefaultTableModel)tblBorrowedBooks.getModel();
             tblModel1.addRow(tblData);
            }
            con.close();
        }catch(Exception e){
            e.printStackTrace();
            System.out.println("Error"+e.getLocalizedMessage());
        }
    }//GEN-LAST:event_tblMembersMouseClicked

    private void tblBorrowedBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBorrowedBooksMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel=(DefaultTableModel)tblBorrowedBooks.getModel();
        int selectedRowIndex=tblBorrowedBooks.getSelectedRow();
        txtBookId.setText(tblModel.getValueAt(selectedRowIndex, 1).toString());
        
        ReturnBook returnBook=new ReturnBook();
        float dailyFineRate=5;
        txtFine.setText(String.valueOf(returnBook.calDays(txtMemberId.getText(), txtBookId.getText())*dailyFineRate));
    }//GEN-LAST:event_tblBorrowedBooksMouseClicked

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        if(txtBookId.getText().length()==0 || txtMemberId.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Please select the Member ID and Book ID", "Error ", JOptionPane.ERROR_MESSAGE);
        }else{
        ReturnBook returnBook=new ReturnBook();
        returnBook.returnBookToLibrary(txtMemberId.getText(), txtBookId.getText());
        txtFine.setText(null);
        txtMemberId.setText(null);
        txtBookId.setText(null);
        }
        
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookReturning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookReturning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookReturning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookReturning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BookReturning dialog = new BookReturning(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSearchMember;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBookId;
    private javax.swing.JLabel lblFine;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblMemberId;
    private javax.swing.JLabel lblSearch1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JTable tblBorrowedBooks;
    private javax.swing.JTable tblMembers;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtFine;
    private javax.swing.JTextField txtMemberId;
    private javax.swing.JTextField txtSearchMember;
    // End of variables declaration//GEN-END:variables
}
