/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        super("Library Management System");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUsers = new javax.swing.JMenu();
        itmAddUser = new javax.swing.JMenuItem();
        itmViewUsers = new javax.swing.JMenuItem();
        mnuBooks = new javax.swing.JMenu();
        itmAddNewBook = new javax.swing.JMenuItem();
        itmBorrow = new javax.swing.JMenuItem();
        itmReturn = new javax.swing.JMenuItem();
        itmBorrowedBooks = new javax.swing.JMenuItem();
        mnuMembers = new javax.swing.JMenu();
        itmAddNewMember = new javax.swing.JMenuItem();
        itmViewMembers = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 51));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 50, 796, 422);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 153));

        mnuUsers.setText("Users");

        itmAddUser.setText("Add New User");
        itmAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddUserActionPerformed(evt);
            }
        });
        mnuUsers.add(itmAddUser);

        itmViewUsers.setText("View/Remove Users");
        itmViewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmViewUsersActionPerformed(evt);
            }
        });
        mnuUsers.add(itmViewUsers);

        jMenuBar1.add(mnuUsers);

        mnuBooks.setText("Books");

        itmAddNewBook.setText("Add New Book");
        itmAddNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddNewBookActionPerformed(evt);
            }
        });
        mnuBooks.add(itmAddNewBook);

        itmBorrow.setText("View/Borrow Books");
        itmBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBorrowActionPerformed(evt);
            }
        });
        mnuBooks.add(itmBorrow);

        itmReturn.setText("Return Books");
        itmReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmReturnActionPerformed(evt);
            }
        });
        mnuBooks.add(itmReturn);

        itmBorrowedBooks.setText("Borrowed Books Reports");
        itmBorrowedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBorrowedBooksActionPerformed(evt);
            }
        });
        mnuBooks.add(itmBorrowedBooks);

        jMenuBar1.add(mnuBooks);

        mnuMembers.setText("Members");

        itmAddNewMember.setText("Add New Member");
        itmAddNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddNewMemberActionPerformed(evt);
            }
        });
        mnuMembers.add(itmAddNewMember);

        itmViewMembers.setText("View Members");
        itmViewMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmViewMembersActionPerformed(evt);
            }
        });
        mnuMembers.add(itmViewMembers);

        jMenuBar1.add(mnuMembers);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(814, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddUserActionPerformed
        // TODO add your handling code here:
        if(User.isAdmin){
        UserRegistration userRegistration=new UserRegistration(this, true);
        userRegistration.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Sorry only Admin can Add New Users to the System", "InfoBox: " + "Login", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itmAddUserActionPerformed

    private void itmViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmViewUsersActionPerformed
        // TODO add your handling code here:
        ViewUsers viewUsers=new ViewUsers(this, true);
        viewUsers.setVisible(true);
    }//GEN-LAST:event_itmViewUsersActionPerformed

    private void itmAddNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddNewBookActionPerformed
        // TODO add your handling code here:
        BookRegistration bookRegistration=new BookRegistration(this, true);
        bookRegistration.setVisible(true);
    }//GEN-LAST:event_itmAddNewBookActionPerformed

    private void itmAddNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddNewMemberActionPerformed
        // TODO add your handling code here:
        MemberRegistration memberRegistration=new MemberRegistration(this, true);
        memberRegistration.setVisible(true);
    }//GEN-LAST:event_itmAddNewMemberActionPerformed

    private void itmBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBorrowActionPerformed
        // TODO add your handling code here:
        BorrowBooks borrowBooks=new BorrowBooks(this, true);
        borrowBooks.setVisible(true);
    }//GEN-LAST:event_itmBorrowActionPerformed

    private void itmReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmReturnActionPerformed
        // TODO add your handling code here:
        BookReturning bookReturning=new BookReturning(this, true);
        bookReturning.setVisible(true);
    }//GEN-LAST:event_itmReturnActionPerformed

    private void itmBorrowedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBorrowedBooksActionPerformed
        // TODO add your handling code here:
        BorrowedBooksView borrowedBooksView=new BorrowedBooksView(this, true);
        borrowedBooksView.setVisible(true);
    }//GEN-LAST:event_itmBorrowedBooksActionPerformed

    private void itmViewMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmViewMembersActionPerformed
        // TODO add your handling code here:
        ViewMembers viewMembers=new ViewMembers(this, true);
        viewMembers.setVisible(true);
    }//GEN-LAST:event_itmViewMembersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAddNewBook;
    private javax.swing.JMenuItem itmAddNewMember;
    private javax.swing.JMenuItem itmAddUser;
    private javax.swing.JMenuItem itmBorrow;
    private javax.swing.JMenuItem itmBorrowedBooks;
    private javax.swing.JMenuItem itmReturn;
    private javax.swing.JMenuItem itmViewMembers;
    private javax.swing.JMenuItem itmViewUsers;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuBooks;
    private javax.swing.JMenu mnuMembers;
    private javax.swing.JMenu mnuUsers;
    // End of variables declaration//GEN-END:variables
}
